mysite/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'account'
urlpatterns = [

    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

mysite/mainapp/urls.py
from django.urls import path
from . import views




urlpatterns = [
    path('',views.index,name="home"),
    path('collection',views.collection,name="collection"),
    path('about',views.about,name="about"),
    path('contact', views.Contactview.as_view(), name="contact"),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Jewellery Shop Admin"
admin.site.site_header = "Jewellery Shop Admin Portal"
admin.site.index_title = "Welcome to Jewellery shop"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('account/', include('account.urls'))
]

mysite/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager, User
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    MALE = 'male'
    FEMALE = 'female'

    GENDER_CHOICES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    Address = models.TextField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=30, null=True, blank=True)
    state = models.CharField(max_length=30, null=True, blank=True)
    contact_number = models.CharField(max_length=20, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def has_module_perms(self, app_label):
        return True

mysite/mainapp/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    phone = models.CharField(max_length=12)
    desc = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

mysite/account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from account.models import CustomUser


class RegistrationForm(forms.ModelForm):
    address = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control", "placeholder": "address"}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': "form-control", "placeholder": "confirm password"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': "form-control", "placeholder": "Enter Your  password"}))

    class Meta:
        model = CustomUser
        fields = ["username", "gender", "address", "city", "state", "email", "contact_number", "password"]

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Name",
            }
        )
        self.fields['gender'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Gender",
            }
        )
        self.fields['city'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your city",
            }
        )
        self.fields['state'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your state",
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your email'id",
            }
        )
        self.fields['contact_number'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Contact number",
            }
        )

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password == password2:
            return cleaned_data

    def save(self, commit=True):
        instance = super(RegistrationForm, self).save(commit=False)
        instance.set_password(self.cleaned_data["password"])
        return super(RegistrationForm, self).save(commit=commit)


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Username ",
            }
        )
        self.fields['password'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Password ",
            }
        )

mysite/mainapp/forms.py
from django import forms
from mainapp.models import Contact


class ContactForm(forms.ModelForm):
    desc = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control","placeholder":"tell me about contact me",}))

    class Meta:
        model = Contact
        fields = ["name", "email", "phone", "desc"]

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Name",
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your email'id",
            }
        )
        self.fields['phone'].widget.attrs.update(
            {
                'class': "form-control",
                'placeholder': "Enter Your Contact Number",
            }
        )

mysite/account/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from account.forms import RegistrationForm, CustomLoginForm
from django.contrib.auth.views import LoginView


# Create your views here.

class RegisterView(CreateView):
    form_class = RegistrationForm
    template_name = 'account/register.html'
    success_url = reverse_lazy('account:register')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CustomLoginView(LoginView):
    form_class = CustomLoginForm
    template_name = 'account/login.html'

mysite/mainapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from mainapp.forms import ContactForm
from django.urls import reverse_lazy


# Create your views here.

def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def collection(request):
    return render(request, 'collection.html')


class Contactview(CreateView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('contact')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

mysite/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block body %} <!-- About us -->

<!--<div class="container-fluid px-0 mb-3">
    <img src="https://source.unsplash.com/1200x400/?about,shop" class="d-block w-100 mx-0" alt="...">
</div>-->
<div class="container py-5 mb-5">
    <h2 class="text-center">About Us</h2>
  </div>
    <p>
										The About Us page of your shop is vital because it’s where users go when first trying to determine a level of trust. Since trust is such an important part of selling online, it’s a good idea to give people a fair amount information about yourself and your shop. Here are a few things you should touch on:
									</p>

<!-- Card -DEck -->
<!-- About us -->
<div class="card-deck mb-4 py-5" >
  <div class="card">
      <div class="card-body">
      <h5 class="card-title">About Us</h5>
      <li class="list-unstyled">
          <a href="/contact">Contact us</a>
      </li>
          <li class="list-unstyled">
              <a href="account.html">Map Site</a>
    </li>
      </div>
    <div class="card-footer">
      <!--<small class="text-muted">Last updated 3 mins ago</small>-->
    </div>
  </div><!-- Information -->
  <div class="card">
      <div class="card-body">
      <h5 class="card-title">Information</h5>
      <li class="list-unstyled">
          <a href="#">Advance Search </a>
      </li>
          <li class="list-unstyled">
              <a href="#">Shop By Brand</a>
    </li>
    </div>
     <div class="card-footer"></div>
  </div><!-- account -->
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Account</h5>
    <li class="list-unstyled">
          <a href="#">Order History</a>
      </li>
          <li class="list-unstyled">
              <a href="#">Sign in</a>
    </li>
        <li class="list-unstyled">
              <a href="#">Cart Page</a>
    </li>
    </div>
    <div class="card-footer"></div>
  </div>
</div>
			<div class="footer-content footer-content-bottom clearfix" align="Center">
				<div class="container">
					<div class="copyright col-md-12">
						<a href="about.html">Jewelry shop</a>.@ All Rights Reserved.
					</div>

				</div>
			</div>
</div>
{% endblock body %}

mysite/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %} | Jewelley shop</title>
  </head>
  <body>

  <!--nav bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Jewellary Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
             <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="account/" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'account:register' %}">Register</a>
              <a class="dropdown-item" href="{% url 'account:login' %}">Login</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About Us</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/collection" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Collection
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/collection">Ring</a>
              <a class="dropdown-item" href="#">Earrings</a>
              <a class="dropdown-item" href="#">Neckless</a>
               <a class="dropdown-item" href="#">Bracelets</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact Us</a>
          </li>
        </ul>
        <div class="ml-auto form-inline">
        <form class="my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/collection" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Welcome {{request.user}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'account:logout' %}">Log Out</a>
            </div>
          </li>
        </ul>

        {% else %}
        <!-- Button trigger modal -->
      <!--  <button type="button" class="btn btn-success mx-2" data-toggle="modal" data-target="#registrationmodal">
          Sign Up
        </button>
-->
        <!-- Button trigger modal -->
         <!--<button type="button" class="btn btn-success" data-toggle="modal" data-target="#loginmodal">
         Log In
        </button>-->
        {% endif %}
        </div>
      </div>
    </nav>


  {% if messages %}
  {% for messages in messages %}
   <div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0 " role="alert">
     <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  {% endfor %}
  {% endif %}
    {% block body %} {% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


  </body>

</html>

mysite/templates/collection.html
{% extends 'base.html' %}

{% block title %}Product{% endblock title %}

{% block body %} {% endblock body %}

mysite/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock title %}

{% block body %}
<div class="container-fluid px-0 mb-3">
    <img src="https://source.unsplash.com/1200x400/?phone,contact" class="d-block w-100 mx-0" alt="...">
</div>

<div class="container py-4 mb-3">
 <h2 class="text-center">Contact Us</h2>
    <form method="post">
        {% csrf_token %}

        <div class="form-group">
            {{ form.name.errors }}
            <label for="id_name">{{ form.name.label_tag }}</label>
            {{ form.name }}
        </div>
  <div class="form-group">
    <label for="id_email">{{ form.email.label_tag }}</label>
    {{ form.email }}
  </div>
  <div class="form-group">
    <label for="id_phone">{{ form.phone.label_tag }}</label>
   {{ form.phone }}
  </div>
    <div class="form-group">
    <label for="id_desc">{{ form.desc.label_tag }}</label>
    {{ form.desc }}
  </div>
        <button  class="btn btn-primary" type="submit" value="submit">Submit</button>
</form>

{% endblock body %}

mysite/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}
{% load static %}
{% block body %}

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner my-2">
    <div class="carousel-item active" style="height: 35em;">
      <img src="{% static 'img/home4-slide1e11bf.jpg'%}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Welcome To Jewellary Shop</h5>
        <!--<p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>-->
      </div>
    </div>
    <div class="carousel-item "style="height: 35em;">
      <img src="{% static 'img/slid-2.jpg'%}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>World best Collection of Jewellary</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
    </div>
  <div class="carousel-item" style="height: 35em;">
      <img src="{% static 'img/slid-1.jpg'%}"class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Inaugurated by Donald Trump</h5>
        <p>This Jewellary shop was Inaugurated by Donald Trump .</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>




  <div class="container my-3">
<h1 class="my-4 text-center">Top Collections</h1>
    <div class="row">
      <div class="col-md-4" style="height: 6em;">
        <div class="card mb-4 shadow-sm">
          <img src="{% static 'img/4_b760c006-b403-4035-ba94-b19cb0ff8214_1024x1024c150.jpg'%}" class="d-block w-100" alt="...">
          <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
          </div>
        </div>
      </div>


      <div class="col-md-4" style="height: 6em;">
        <div class="card mb-4 shadow-sm">
          <img src="{% static 'img/product2.jpg'%}" class="d-block w-100" alt="...">
          <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
          </div>
        </div>
      </div>


      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{% static 'img/product10.jpg'%}" class="d-block w-100" alt="...">
          <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
          </div>
        </div>
      </div>


      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{% static 'img/6_2b8df768-6599-4e41-ae4c-2d6afd2b1d95_1024x10247cf8.jpg'%}" class="d-block w-100" alt="...">
          <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
          </div>
        </div>
      </div>


      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{% static 'img/product4.jpg'%}" class="d-block w-100" alt="...">
          <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
          </div>
        </div>
      </div>


      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{% static 'img/product5.jpg'%}" class="d-block w-100" alt="...">
          <div class="card-body">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock body %}

mysite/templates/logout.html
<h1>logout</h1>

mysite/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock title %}
{% block content %}
    <form method="POST" class="form-group">
	{% csrf_token %}

	<button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock %}